version: "3.5"

services:
  notenic-api:
    build:
      context: ./notenic-api
      args:
        - NODE_ENV=development
    image: notenic-api
    container_name: notenic-api
    ports:
      - "3000:3000"
    volumes:
      - ./notenic-api:/app
      - notenic-api_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - notenic-postgres
      - notenic-nats

  notenic-files:
    build:
      context: ./notenic-files
      args:
        - NODE_ENV=development
    image: notenic-files
    container_name: notenic-files
    ports:
      - "3001:3001"
    volumes:
      - ./notenic-files:/app
      - notenic-files_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development

  notenic-notifications:
    build:
      context: ./notenic-notifications
      args:
        - NODE_ENV=development
    image: notenic-notifications
    container_name: notenic-notifications
    ports:
      - "3002:3002"
    volumes:
      - ./notenic-notifications:/app
      - notenic-notifications_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development

  notenic-postgres:
    image: postgres:11.4-alpine
    container_name: notenic-postgres
    ports:
    - "5000:5432"
    environment:
    - POSTGRES_USER=root
    - POSTGRES_PASSWORD=root
    - POSTGRES_DB=notenic

  notenic-frontend:
    build:
      context: ./notenic-frontend
      args:
        - NODE_ENV=development
    image: notenic-frontend
    container_name: notenic-frontend
    ports:
      - "4200:4200"
      - "49153:49153"
    volumes:
      - ./notenic-frontend:/app
      - notenic-frontend_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - notenic-api

  notenic-nats:
    image: nats:2.1.0
    container_name: notenic-nats
    expose:
      - "4222"
    ports:
      - "8222:8222"

volumes:
  notenic-api_node_modules: {}
  notenic-files_node_modules: {}
  notenic-notifications_node_modules: {}
  notenic-frontend_node_modules: {}
